"""Updated water intake name

Revision ID: 7d51a4be0c08
Revises: 59da8b68d674
Create Date: 2023-06-12 09:03:00.364052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7d51a4be0c08"
down_revision = "59da8b68d674"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("water_intake")
    op.execute(
        "ALTER TABLE users ALTER COLUMN activity_level TYPE activitylevels "
        "USING activity_level::activitylevels"
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        # Alter the column type and convert the values

        batch_op.create_unique_constraint(None, ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "activity_level",
            existing_type=sa.Enum(
                "SEDENTARY",
                "LIGHTLY_ACTIVE",
                "MODERATELY_ACTIVE",
                "VERY_ACTIVE",
                name="activitylevels",
            ),
            type_=sa.VARCHAR(),
            existing_nullable=True,
            using="activity_level::varchar",
        )

    op.create_table(
        "water_intake",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="water_intake_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="water_intake_pkey"),
    )
    # ### end Alembic commands ###
